//! Generates FFT golden vectors in text format for Zig cross-validation.
//!
//! NOTE: This uses a naive DFT reference implementation. The authoritative
//! golden vectors in `../vectors/rust_fft_golden_vectors.txt` were originally
//! generated by `aec3-rs/examples/gen_fft_golden.rs` using an optimized FFT.
//! Re-running this tool will produce slightly different values due to
//! floating-point ordering differences. Only use this to regenerate vectors
//! if you have verified the output against the Zig FFT tests.
//!
//! The Zig golden suite in `golden_test/zig/fft.zig` consumes these vectors.

use std::f32::consts::PI;

fn main() {
    gen_aec3_zero_padded();
    gen_ns_256();
}

// ── AEC3: 64-sample input → zero-padded 128-point FFT ──

fn gen_aec3_zero_padded() {
    const N_HALF: usize = 64;
    const N: usize = 128;

    // Input signal (same formula as Zig test)
    let mut input = [0.0f32; N_HALF];
    for i in 0..N_HALF {
        let x = i as f32;
        input[i] =
            0.35 * (x * 0.13).sin() + 0.2 * (x * 0.07).cos() + ((i as i32 - 32) as f32 / 512.0);
    }

    // Zero-pad to 128
    let mut padded = [0.0f32; N];
    padded[..N_HALF].copy_from_slice(&input);

    print_vector("AEC3_ZERO_PADDED_INPUT64", &input);

    // Forward real FFT (DFT)
    let (re, im) = real_dft(&padded, N_HALF + 1);
    print_vector("AEC3_ZERO_PADDED_RE65", &re);
    print_vector("AEC3_ZERO_PADDED_IM65", &im);

    // Inverse FFT
    let ifft_out = real_idft(&re, &im, N);
    print_vector("AEC3_ZERO_PADDED_IFFT128", &ifft_out);
}

// ── NS: 256-point FFT ──

fn gen_ns_256() {
    const N: usize = 256;
    const N_HALF_PLUS_1: usize = 129;

    let mut input = [0.0f32; N];
    for i in 0..N {
        let x = i as f32;
        input[i] =
            0.4 * (x * 0.11).sin() - 0.15 * (x * 0.05).cos() + ((i as i32 - 128) as f32 / 1024.0);
    }

    print_vector("NS_INPUT256", &input);

    let (re, im) = real_dft(&input, N_HALF_PLUS_1);
    print_vector("NS_RE129", &re);
    print_vector("NS_IM129", &im);

    let ifft_out = real_idft(&re, &im, N);
    print_vector("NS_IFFT256", &ifft_out);
}

// ── Naive DFT (reference, not optimized) ──

fn real_dft(x: &[f32], num_bins: usize) -> (Vec<f32>, Vec<f32>) {
    let n = x.len();
    let mut re = vec![0.0f32; num_bins];
    let mut im = vec![0.0f32; num_bins];
    for k in 0..num_bins {
        for i in 0..n {
            let angle = 2.0 * PI * (k as f32) * (i as f32) / (n as f32);
            re[k] += x[i] * angle.cos();
            im[k] -= x[i] * angle.sin();
        }
    }
    (re, im)
}

fn real_idft(re: &[f32], im: &[f32], n: usize) -> Vec<f32> {
    let num_bins = re.len();
    let mut out = vec![0.0f32; n];
    for i in 0..n {
        let mut sum = 0.0f32;
        for k in 0..num_bins {
            let angle = 2.0 * PI * (k as f32) * (i as f32) / (n as f32);
            sum += re[k] * angle.cos() - im[k] * angle.sin();
            // Add conjugate mirror bins (except DC and Nyquist)
            if k > 0 && k < num_bins - 1 {
                sum += re[k] * angle.cos() + im[k] * angle.sin();
            }
        }
        out[i] = sum / (n as f32);
    }
    out
}

fn print_vector(name: &str, data: &[f32]) {
    println!("BEGIN {} {}", name, data.len());
    for (i, v) in data.iter().enumerate() {
        println!("{}[{}]={:.9}", name, i, v);
    }
    println!("END {}", name);
}
