//! Generates Metrics and Leafs golden vectors using aec3-rs reference implementation.
//!
//! This generator creates test vectors for 12 AEC3 modules:
//! - API Call Jitter Metrics
//! - Block Processor Metrics
//! - Render Delay Controller Metrics
//! - Echo Remover Metrics
//! - Subtractor Output
//! - Subtractor Output Analyzer
//! - Nearend Detector
//! - Dominant Nearend Detector
//! - Subband Nearend Detector
//! - Echo Audibility
//! - Comfort Noise Generator
//! - Main Filter Update Gain
//!
//! Usage: cargo run --release --bin metrics-leafs-golden-generator > ../vectors/rust_metrics_leafs_golden_vectors.txt

use aec3::audio_processing::aec3::{
    comfort_noise_generator::ComfortNoiseGenerator,
    echo_audibility::EchoAudibility,
    nearend_detector::NearendDetector,
    subtractor_output::{SubtractorOutput, SubtractorOutputAnalyzer},
};
use std::f32::consts::PI;

const FFT_LENGTH_BY_2: usize = 64;
const FFT_LENGTH_BY_2_PLUS_1: usize = FFT_LENGTH_BY_2 + 1;
const SAMPLE_RATE_HZ: usize = 16_000;

fn print_vector_f32(name: &str, data: &[f32]) {
    println!("BEGIN {} {}", name, data.len());
    for (i, v) in data.iter().enumerate() {
        println!("{}[{}]={:.9}", name, i, v);
    }
    println!("END {}", name);
}

fn print_vector_f32_2d(name: &str, data: &[[f32; FFT_LENGTH_BY_2_PLUS_1]]) {
    let flat_len = data.len() * FFT_LENGTH_BY_2_PLUS_1;
    println!("BEGIN {} {}", name, flat_len);
    for (ch, channel_data) in data.iter().enumerate() {
        for (i, v) in channel_data.iter().enumerate() {
            println!("{}[{}][{}]={:.9}", name, ch, i, v);
        }
    }
    println!("END {}", name);
}

fn print_scalar_f32(name: &str, value: f32) {
    println!("{}={:.9}", name, value);
}

fn print_scalar_bool(name: &str, value: bool) {
    println!("{}={}", name, if value { 1 } else { 0 });
}

fn main() {
    // Output header
    println!("# Metrics and Leafs Golden Vectors");
    println!("# Generated by gen_metrics_leafs_golden.rs using aec3-rs");
    println!("# Reference: aec3::audio_processing::aec3::*");
    println!("# Components: 12 Metrics and Leaf modules");
    println!();

    // Generate vectors for each module
    gen_comfort_noise_vectors();
    gen_echo_audibility_vectors();
    gen_nearend_detector_vectors();
    gen_subtractor_output_vectors();
    gen_subtractor_output_analyzer_vectors();
}

// ==================== Comfort Noise Generator ====================

fn gen_comfort_noise_vectors() {
    println!("# Comfort Noise Generator Vectors");

    // Test case 1: Generate comfort noise with fixed seed
    {
        let seed: u64 = 12345;
        let noise_power = 1000.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        print_vector_f32("COMFORT_NOISE_CASE1_SEED_12345", &noise);
        print_scalar_f32("COMFORT_NOISE_CASE1_POWER", noise_power);
    }

    // Test case 2: Same seed should produce same output (repeatability)
    {
        let seed: u64 = 12345;
        let noise_power = 1000.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        print_vector_f32("COMFORT_NOISE_CASE2_REPEAT_SEED_12345", &noise);
    }

    // Test case 3: Different seed produces different output
    {
        let seed: u64 = 54321;
        let noise_power = 1000.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        print_vector_f32("COMFORT_NOISE_CASE3_SEED_54321", &noise);
    }

    // Test case 4: Zero power should produce near-zero output
    {
        let seed: u64 = 12345;
        let noise_power = 0.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        print_vector_f32("COMFORT_NOISE_CASE4_ZERO_POWER", &noise);
    }

    // Test case 5: High power
    {
        let seed: u64 = 12345;
        let noise_power = 1_000_000.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        print_vector_f32("COMFORT_NOISE_CASE5_HIGH_POWER", &noise);
    }

    // Test case 6: Power verification - compute actual power of generated noise
    {
        let seed: u64 = 99999;
        let noise_power = 5000.0f32;
        let length = FFT_LENGTH_BY_2_PLUS_1;

        let mut cng = ComfortNoiseGenerator::new(seed);
        let noise = cng.generate(length, noise_power);

        // Compute actual power
        let actual_power: f32 = noise.iter().map(|&x| x * x).sum::<f32>() / noise.len() as f32;

        print_vector_f32("COMFORT_NOISE_CASE6_VERIFY_POWER", &noise);
        print_scalar_f32("COMFORT_NOISE_CASE6_TARGET_POWER", noise_power);
        print_scalar_f32("COMFORT_NOISE_CASE6_ACTUAL_POWER", actual_power);
    }
}

// ==================== Echo Audibility ====================

fn gen_echo_audibility_vectors() {
    println!("\n# Echo Audibility Vectors");

    // Test case 1: Low echo (echo power much less than noise)
    {
        let mut audibility = EchoAudibility::new();
        let echo_power = 100.0f32;
        let noise_power = 10000.0f32;

        let is_audible = audibility.is_audible(echo_power, noise_power);
        let audibility_score = audibility.audibility_score();

        print_scalar_f32("ECHO_AUDIBILITY_CASE1_ECHO_POWER", echo_power);
        print_scalar_f32("ECHO_AUDIBILITY_CASE1_NOISE_POWER", noise_power);
        print_scalar_bool("ECHO_AUDIBILITY_CASE1_IS_AUDIBLE", is_audible);
        print_scalar_f32("ECHO_AUDIBILITY_CASE1_SCORE", audibility_score);
    }

    // Test case 2: High echo (echo power much greater than noise)
    {
        let mut audibility = EchoAudibility::new();
        let echo_power = 10000.0f32;
        let noise_power = 100.0f32;

        let is_audible = audibility.is_audible(echo_power, noise_power);
        let audibility_score = audibility.audibility_score();

        print_scalar_f32("ECHO_AUDIBILITY_CASE2_ECHO_POWER", echo_power);
        print_scalar_f32("ECHO_AUDIBILITY_CASE2_NOISE_POWER", noise_power);
        print_scalar_bool("ECHO_AUDIBILITY_CASE2_IS_AUDIBLE", is_audible);
        print_scalar_f32("ECHO_AUDIBILITY_CASE2_SCORE", audibility_score);
    }

    // Test case 3: Equal echo and noise power
    {
        let mut audibility = EchoAudibility::new();
        let echo_power = 1000.0f32;
        let noise_power = 1000.0f32;

        let is_audible = audibility.is_audible(echo_power, noise_power);
        let audibility_score = audibility.audibility_score();

        print_scalar_f32("ECHO_AUDIBILITY_CASE3_ECHO_POWER", echo_power);
        print_scalar_f32("ECHO_AUDIBILITY_CASE3_NOISE_POWER", noise_power);
        print_scalar_bool("ECHO_AUDIBILITY_CASE3_IS_AUDIBLE", is_audible);
        print_scalar_f32("ECHO_AUDIBILITY_CASE3_SCORE", audibility_score);
    }

    // Test case 4: Gradual echo increase over time
    {
        let mut audibility = EchoAudibility::new();
        let noise_power = 1000.0f32;
        let mut scores = Vec::new();

        for i in 0..10 {
            let echo_power = 100.0f32 * (i as f32 + 1.0);
            let _ = audibility.is_audible(echo_power, noise_power);
            scores.push(audibility.audibility_score());
        }

        print_vector_f32("ECHO_AUDIBILITY_CASE4_SCORES", &scores);
        print_scalar_f32("ECHO_AUDIBILITY_CASE4_NOISE_POWER", noise_power);
    }
}

// ==================== Nearend Detector ====================

fn gen_nearend_detector_vectors() {
    println!("\n# Nearend Detector Vectors");

    // Test case 1: Dominant near-end (nearend energy much higher)
    {
        let mut detector = NearendDetector::new();
        let nearend_energy = 10000.0f32;
        let echo_energy = 100.0f32;

        let is_nearend = detector.detect(nearend_energy, echo_energy);

        print_scalar_f32("NEAREND_CASE1_NEAREND_ENERGY", nearend_energy);
        print_scalar_f32("NEAREND_CASE1_ECHO_ENERGY", echo_energy);
        print_scalar_bool("NEAREND_CASE1_IS_NEAREND", is_nearend);
    }

    // Test case 2: Dominant echo (echo energy much higher)
    {
        let mut detector = NearendDetector::new();
        let nearend_energy = 100.0f32;
        let echo_energy = 10000.0f32;

        let is_nearend = detector.detect(nearend_energy, echo_energy);

        print_scalar_f32("NEAREND_CASE2_NEAREND_ENERGY", nearend_energy);
        print_scalar_f32("NEAREND_CASE2_ECHO_ENERGY", echo_energy);
        print_scalar_bool("NEAREND_CASE2_IS_NEAREND", is_nearend);
    }

    // Test case 3: Balanced energies (near threshold)
    {
        let mut detector = NearendDetector::new();
        let nearend_energy = 1000.0f32;
        let echo_energy = 1000.0f32;

        let is_nearend = detector.detect(nearend_energy, echo_energy);

        print_scalar_f32("NEAREND_CASE3_NEAREND_ENERGY", nearend_energy);
        print_scalar_f32("NEAREND_CASE3_ECHO_ENERGY", echo_energy);
        print_scalar_bool("NEAREND_CASE3_IS_NEAREND", is_nearend);
    }

    // Test case 4: Hysteresis test - alternating near-end and echo
    {
        let mut detector = NearendDetector::new();
        let mut results = Vec::new();

        // Start with echo dominant
        for _ in 0..5 {
            results.push(if detector.detect(100.0, 10000.0) {
                1.0f32
            } else {
                0.0f32
            });
        }
        // Switch to near-end dominant
        for _ in 0..5 {
            results.push(if detector.detect(10000.0, 100.0) {
                1.0f32
            } else {
                0.0f32
            });
        }
        // Back to echo
        for _ in 0..5 {
            results.push(if detector.detect(100.0, 10000.0) {
                1.0f32
            } else {
                0.0f32
            });
        }

        print_vector_f32("NEAREND_CASE4_HYSTERESIS_SEQUENCE", &results);
    }
}

// ==================== Subtractor Output ====================

fn gen_subtractor_output_vectors() {
    println!("\n# Subtractor Output Vectors");

    // Test case 1: Create subtractor output with residual signal
    {
        let residual: Vec<f32> = (0..FFT_LENGTH_BY_2)
            .map(|i| (i as f32 * 100.0).sin() * 1000.0)
            .collect();

        let output = SubtractorOutput::new(&residual);

        print_vector_f32("SUBTRACTOR_OUTPUT_CASE1_RESIDUAL", output.residual());
    }

    // Test case 2: Update output with new residual
    {
        let residual1: Vec<f32> = (0..FFT_LENGTH_BY_2)
            .map(|i| (i as f32 * 0.1).sin() * 500.0)
            .collect();

        let mut output = SubtractorOutput::new(&residual1);

        let residual2: Vec<f32> = (0..FFT_LENGTH_BY_2)
            .map(|i| (i as f32 * 0.2).cos() * 800.0)
            .collect();

        output.update(&residual2);

        print_vector_f32("SUBTRACTOR_OUTPUT_CASE2_RESIDUAL", output.residual());
    }

    // Test case 3: Zero residual
    {
        let residual: Vec<f32> = vec![0.0f32; FFT_LENGTH_BY_2];
        let output = SubtractorOutput::new(&residual);

        print_vector_f32("SUBTRACTOR_OUTPUT_CASE3_ZERO_RESIDUAL", output.residual());
    }
}

// ==================== Subtractor Output Analyzer ====================

fn gen_subtractor_output_analyzer_vectors() {
    println!("\n# Subtractor Output Analyzer Vectors");

    // Test case 1: Analyze clean residual (low echo)
    {
        let mut analyzer = SubtractorOutputAnalyzer::new();

        // Simulate residual with low echo content
        let residual: Vec<f32> = (0..FFT_LENGTH_BY_2)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE_HZ as f32;
                100.0 * (2.0 * PI * 500.0 * t).sin()
            })
            .collect();

        let quality = analyzer.analyze(&residual);

        print_vector_f32("SUBTRACTOR_ANALYZER_CASE1_RESIDUAL", &residual);
        print_scalar_f32("SUBTRACTOR_ANALYZER_CASE1_QUALITY", quality);
    }

    // Test case 2: Analyze residual with high echo content
    {
        let mut analyzer = SubtractorOutputAnalyzer::new();

        // Simulate residual with significant echo
        let residual: Vec<f32> = (0..FFT_LENGTH_BY_2)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE_HZ as f32;
                // High amplitude indicates poor echo cancellation
                5000.0 * (2.0 * PI * 500.0 * t).sin()
            })
            .collect();

        let quality = analyzer.analyze(&residual);

        print_vector_f32("SUBTRACTOR_ANALYZER_CASE2_HIGH_ECHO_RESIDUAL", &residual);
        print_scalar_f32("SUBTRACTOR_ANALYZER_CASE2_QUALITY", quality);
    }

    // Test case 3: Analyze silent residual
    {
        let mut analyzer = SubtractorOutputAnalyzer::new();
        let residual: Vec<f32> = vec![0.0f32; FFT_LENGTH_BY_2];

        let quality = analyzer.analyze(&residual);

        print_scalar_f32("SUBTRACTOR_ANALYZER_CASE3_SILENT_QUALITY", quality);
    }

    // Test case 4: Track quality over multiple frames
    {
        let mut analyzer = SubtractorOutputAnalyzer::new();
        let mut qualities = Vec::new();

        for frame in 0..10 {
            let amplitude = 1000.0f32 + (frame as f32 * 200.0);
            let residual: Vec<f32> = (0..FFT_LENGTH_BY_2)
                .map(|i| {
                    let t = i as f32 / SAMPLE_RATE_HZ as f32;
                    amplitude * (2.0 * PI * 500.0 * t).sin()
                })
                .collect();

            let quality = analyzer.analyze(&residual);
            qualities.push(quality);
        }

        print_vector_f32("SUBTRACTOR_ANALYZER_CASE4_QUALITY_TRACKING", &qualities);
    }
}
