//! Generates NS (Noise Suppression) golden vectors using aec3-rs reference implementation.
//!
//! Alignment direction: Zig implementation is validated against Rust aec3-rs golden baseline.
//!
//! This calls the official aec3::audio_processing::ns::NoiseSuppressor API
//! to generate authoritative golden vectors for Zig cross-validation.
//!
//! Usage: cargo run --release --bin ns-golden-generator > ../rust_ns_golden_vectors.txt 2>/dev/null

use aec3::audio_processing::audio_buffer::AudioBuffer;
use aec3::audio_processing::ns::noise_suppressor::NoiseSuppressor;
use aec3::audio_processing::ns::ns_config::{NsConfig, SuppressionLevel};
use std::f32::consts::PI;

const FRAME_SIZE: usize = 160;
const FFT_SIZE: usize = 256;
const SAMPLE_RATE_HZ: usize = 16_000;

fn should_run_case(case: &str) -> bool {
    match std::env::var("NS_CASE") {
        Ok(v) => {
            let s = v.to_ascii_lowercase();
            s == "all" || s == case
        }
        Err(_) => true,
    }
}

fn print_vector_f32(name: &str, data: &[f32]) {
    println!("BEGIN {} {}", name, data.len());
    for (i, v) in data.iter().enumerate() {
        println!("{}[{}]={:.9}", name, i, v);
    }
    println!("END {}", name);
}

fn main() {
    // Output header only (no cargo logs)
    println!("# NS (Noise Suppression) Golden Vectors");
    println!("# Generated by gen_ns_golden.rs using aec3-rs");
    println!("# Reference: aec3::audio_processing::ns::NoiseSuppressor");
    println!("# Components: Official aec3-rs NS implementation");
    println!("# Covers: silence, low amplitude, near full scale, speech+noise");
    println!();

    // Case 1: Silence (all zeros)
    if should_run_case("silence") {
        let config = NsConfig {
            target_level: SuppressionLevel::K12dB,
            analyze_linear_aec_output_when_available: false,
        };
        let mut ns = NoiseSuppressor::new(config, SAMPLE_RATE_HZ, 1);
        let mut capture =
            AudioBuffer::from_sample_rates(SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ);

        // Warm-up with silence
        for _ in 0..5 {
            capture.channel_mut(0).iter_mut().for_each(|x| *x = 0.0);
            ns.analyze(&capture);
            ns.process(&mut capture);
        }

        // Final pass with fresh silence
        capture.channel_mut(0).iter_mut().for_each(|x| *x = 0.0);
        let input: Vec<f32> = capture.channel(0).iter().copied().collect();
        ns.analyze(&capture);
        ns.process(&mut capture);
        let output: Vec<f32> = capture.channel(0).iter().copied().collect();

        print_vector_f32("NS_SILENCE_INPUT", &input);
        print_vector_f32("NS_SILENCE_OUTPUT", &output);
    }

    // Case 2: Low amplitude signal
    if should_run_case("lowamp") {
        let config = NsConfig {
            target_level: SuppressionLevel::K12dB,
            analyze_linear_aec_output_when_available: false,
        };
        let mut ns = NoiseSuppressor::new(config, SAMPLE_RATE_HZ, 1);
        let mut capture =
            AudioBuffer::from_sample_rates(SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ);

        // Generate low amplitude sine wave
        let input: Vec<f32> = (0..FRAME_SIZE)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE_HZ as f32;
                0.001 * (2.0 * PI * 500.0 * t).sin()
            })
            .collect();

        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        print_vector_f32("NS_LOWAMP_INPUT", &input);

        // Warm-up
        for _ in 0..5 {
            capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
            ns.analyze(&capture);
            ns.process(&mut capture);
        }

        // Final pass with fresh input
        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        ns.analyze(&capture);
        ns.process(&mut capture);
        let output: Vec<f32> = capture.channel(0)[..FRAME_SIZE].iter().copied().collect();

        print_vector_f32("NS_LOWAMP_OUTPUT", &output);
    }

    // Case 3: Near full scale signal
    if should_run_case("fullscale") {
        let config = NsConfig {
            target_level: SuppressionLevel::K12dB,
            analyze_linear_aec_output_when_available: false,
        };
        let mut ns = NoiseSuppressor::new(config, SAMPLE_RATE_HZ, 1);
        let mut capture =
            AudioBuffer::from_sample_rates(SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ);

        // Generate near full scale sine wave
        let input: Vec<f32> = (0..FRAME_SIZE)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE_HZ as f32;
                0.9 * (2.0 * PI * 1000.0 * t).sin()
            })
            .collect();

        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        print_vector_f32("NS_FULLSCALE_INPUT", &input);

        // Warm-up
        for _ in 0..5 {
            capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
            ns.analyze(&capture);
            ns.process(&mut capture);
        }

        // Final pass with fresh input
        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        ns.analyze(&capture);
        ns.process(&mut capture);
        let output: Vec<f32> = capture.channel(0)[..FRAME_SIZE].iter().copied().collect();

        print_vector_f32("NS_FULLSCALE_OUTPUT", &output);
    }

    // Case 4: Speech + noise (mixed signal)
    if should_run_case("speechnoise") {
        let config = NsConfig {
            target_level: SuppressionLevel::K12dB,
            analyze_linear_aec_output_when_available: false,
        };
        let mut ns = NoiseSuppressor::new(config, SAMPLE_RATE_HZ, 1);
        let mut capture =
            AudioBuffer::from_sample_rates(SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ, 1, SAMPLE_RATE_HZ);

        // Generate speech-like signal (multiple harmonics) + noise
        let input: Vec<f32> = (0..FRAME_SIZE)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE_HZ as f32;
                let speech = 0.3 * (2.0 * PI * 200.0 * t).sin()
                    + 0.15 * (2.0 * PI * 400.0 * t).sin()
                    + 0.08 * (2.0 * PI * 800.0 * t).sin();
                let noise = 0.05 * ((i % 7) as f32 - 3.0) / 3.0;
                speech + noise
            })
            .collect();

        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        print_vector_f32("NS_SPEECHNOISE_INPUT", &input);

        // Warm-up
        for _ in 0..10 {
            capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
            ns.analyze(&capture);
            ns.process(&mut capture);
        }

        // Final pass with fresh input
        capture.channel_mut(0)[..FRAME_SIZE].copy_from_slice(&input);
        ns.analyze(&capture);
        ns.process(&mut capture);
        let output: Vec<f32> = capture.channel(0)[..FRAME_SIZE].iter().copied().collect();

        print_vector_f32("NS_SPEECHNOISE_OUTPUT", &output);
    }
}
