//! Generates NS (Noise Suppression) golden vectors for Zig cross-validation.
//!
//! This generates golden vectors for the NS main chain: analyze() + process()
//! covering boundary conditions: silence, low amplitude, near full scale, speech+noise.
//!
//! Usage: cargo run --release --bin ns-golden-generator > testdata/rust_ns_golden_vectors.txt

use std::f32::consts::PI;

const FFT_SIZE: usize = 256;
const FFT_SIZE_BY_2_PLUS_1: usize = 129;
const FRAME_SIZE: usize = FFT_SIZE;
const SAMPLE_RATE_HZ: f32 = 16_000.0;

/// Simplified noise suppressor for golden vector generation
struct NoiseSuppressorGolden {
    noise_floor: f32,
    prev_gain: [f32; FFT_SIZE_BY_2_PLUS_1],
    noise_estimate: [f32; FFT_SIZE_BY_2_PLUS_1],
}

impl NoiseSuppressorGolden {
    fn new(noise_floor: f32) -> Self {
        Self {
            noise_floor,
            prev_gain: [1.0; FFT_SIZE_BY_2_PLUS_1],
            noise_estimate: [noise_floor; FFT_SIZE_BY_2_PLUS_1],
        }
    }

    fn analyze(&mut self, frame: &[f32; FRAME_SIZE]) {
        let (real, imag) = self.fft(frame);

        // Compute magnitude squared
        let mut magnitude2 = [0.0f32; FFT_SIZE_BY_2_PLUS_1];
        for i in 0..FFT_SIZE_BY_2_PLUS_1 {
            magnitude2[i] = real[i] * real[i] + imag[i] * imag[i];
        }

        // Simple noise estimation (exponential smoothing)
        for i in 0..FFT_SIZE_BY_2_PLUS_1 {
            self.noise_estimate[i] = 0.9 * self.noise_estimate[i] + 0.1 * magnitude2[i];
            self.noise_estimate[i] = self.noise_estimate[i].max(self.noise_floor);
        }
    }

    fn process(&mut self, frame: &mut [f32; FRAME_SIZE]) {
        let (mut real, mut imag) = self.fft(frame);

        // Compute magnitude squared
        let mut magnitude2 = [0.0f32; FFT_SIZE_BY_2_PLUS_1];
        for i in 0..FFT_SIZE_BY_2_PLUS_1 {
            magnitude2[i] = real[i] * real[i] + imag[i] * imag[i];
        }

        // Compute prior SNR and speech probability
        let mut prior_snr = [0.0f32; FFT_SIZE_BY_2_PLUS_1];
        let mut speech_prob = [0.0f32; FFT_SIZE_BY_2_PLUS_1];

        for i in 0..FFT_SIZE_BY_2_PLUS_1 {
            // Prior SNR estimate
            let posterior_snr = magnitude2[i] / self.noise_estimate[i];
            let prior = self.prev_gain[i] * self.prev_gain[i];
            prior_snr[i] = 0.98 * prior + 0.02 * (posterior_snr - 1.0).max(0.0);

            // Speech probability using sigmoid
            let x = 0.5 * (prior_snr[i] - 1.0);
            speech_prob[i] = 0.5 * (1.0 + x.tanh());

            // Wiener filter gain
            let gain = prior_snr[i] / (prior_snr[i] + 1.0) * speech_prob[i];
            let gain = gain.clamp(0.0, 1.0);

            real[i] *= gain;
            imag[i] *= gain;
            self.prev_gain[i] = gain;
        }

        // IFFT
        let out = self.ifft(&real, &imag);

        // Output with scaling (matching Zig implementation)
        for i in 0..FRAME_SIZE {
            frame[i] = (out[i] * 0.5).clamp(-1.0, 1.0);
        }
    }

    fn fft(
        &self,
        input: &[f32; FFT_SIZE],
    ) -> ([f32; FFT_SIZE_BY_2_PLUS_1], [f32; FFT_SIZE_BY_2_PLUS_1]) {
        let mut re = [0.0f32; FFT_SIZE_BY_2_PLUS_1];
        let mut im = [0.0f32; FFT_SIZE_BY_2_PLUS_1];

        for k in 0..FFT_SIZE_BY_2_PLUS_1 {
            for i in 0..FFT_SIZE {
                let angle = 2.0 * PI * (k as f32) * (i as f32) / (FFT_SIZE as f32);
                re[k] += input[i] * angle.cos();
                im[k] -= input[i] * angle.sin();
            }
        }

        (re, im)
    }

    fn ifft(
        &self,
        re: &[f32; FFT_SIZE_BY_2_PLUS_1],
        im: &[f32; FFT_SIZE_BY_2_PLUS_1],
    ) -> [f32; FFT_SIZE] {
        let mut out = [0.0f32; FFT_SIZE];

        for i in 0..FFT_SIZE {
            let mut sum = 0.0f32;
            for k in 0..FFT_SIZE_BY_2_PLUS_1 {
                let angle = 2.0 * PI * (k as f32) * (i as f32) / (FFT_SIZE as f32);
                sum += re[k] * angle.cos() - im[k] * angle.sin();
                if k > 0 && k < FFT_SIZE_BY_2_PLUS_1 - 1 {
                    sum += re[k] * angle.cos() + im[k] * angle.sin();
                }
            }
            out[i] = sum / (FFT_SIZE as f32);
        }

        out
    }
}

fn print_vector_f32(name: &str, data: &[f32]) {
    println!("BEGIN {} {}", name, data.len());
    for (i, v) in data.iter().enumerate() {
        println!("{}[{}]={:.9}", name, i, v);
    }
    println!("END {}", name);
}

fn main() {
    println!("# NS (Noise Suppression) Golden Vectors");
    println!("# Generated by gen_ns_golden.rs");
    println!("# Covers: silence, low amplitude, near full scale, speech+noise");
    println!();

    // Case 1: Silence (all zeros)
    {
        let mut ns = NoiseSuppressorGolden::new(1e-10);
        let mut frame = [0.0f32; FRAME_SIZE];

        // Warm-up
        for _ in 0..5 {
            ns.analyze(&frame);
            ns.process(&mut frame);
        }

        // Final pass
        ns.analyze(&frame);
        ns.process(&mut frame);

        print_vector_f32("NS_SILENCE_INPUT", &frame);

        // After processing, silence should remain close to silence
        let output = frame;
        print_vector_f32("NS_SILENCE_OUTPUT", &output);

        // Noise estimate
        print_vector_f32("NS_SILENCE_NOISE", &ns.noise_estimate);
    }

    // Case 2: Low amplitude signal
    {
        let mut ns = NoiseSuppressorGolden::new(1e-10);
        let mut frame = [0.0f32; FRAME_SIZE];

        // Generate low amplitude sine wave
        for i in 0..FRAME_SIZE {
            let t = i as f32 / SAMPLE_RATE_HZ;
            frame[i] = 0.001 * (2.0 * PI * 500.0 * t).sin();
        }

        let input = frame.clone();
        print_vector_f32("NS_LOWAMP_INPUT", &input);

        // Warm-up
        for _ in 0..5 {
            ns.analyze(&frame);
            ns.process(&mut frame);
        }

        // Final pass
        ns.analyze(&frame);
        ns.process(&mut frame);

        print_vector_f32("NS_LOWAMP_OUTPUT", &frame);
        print_vector_f32("NS_LOWAMP_NOISE", &ns.noise_estimate);
    }

    // Case 3: Near full scale signal
    {
        let mut ns = NoiseSuppressorGolden::new(1e-10);
        let mut frame = [0.0f32; FRAME_SIZE];

        // Generate near full scale sine wave
        for i in 0..FRAME_SIZE {
            let t = i as f32 / SAMPLE_RATE_HZ;
            frame[i] = 0.9 * (2.0 * PI * 1000.0 * t).sin();
        }

        let input = frame.clone();
        print_vector_f32("NS_FULLSCALE_INPUT", &input);

        // Warm-up
        for _ in 0..5 {
            ns.analyze(&frame);
            ns.process(&mut frame);
        }

        // Final pass
        ns.analyze(&frame);
        ns.process(&mut frame);

        print_vector_f32("NS_FULLSCALE_OUTPUT", &frame);
        print_vector_f32("NS_FULLSCALE_NOISE", &ns.noise_estimate);
    }

    // Case 4: Speech + noise (mixed signal)
    {
        let mut ns = NoiseSuppressorGolden::new(1e-10);
        let mut frame = [0.0f32; FRAME_SIZE];

        // Generate speech-like signal (multiple harmonics) + noise
        for i in 0..FRAME_SIZE {
            let t = i as f32 / SAMPLE_RATE_HZ;
            let speech = 0.3 * (2.0 * PI * 200.0 * t).sin()
                + 0.15 * (2.0 * PI * 400.0 * t).sin()
                + 0.08 * (2.0 * PI * 800.0 * t).sin();
            let noise = 0.05 * ((i % 7) as f32 - 3.0) / 3.0; // Simple pseudo-random noise
            frame[i] = speech + noise;
        }

        let input = frame.clone();
        print_vector_f32("NS_SPEECHNOISE_INPUT", &input);

        // Warm-up and track
        for _ in 0..10 {
            ns.analyze(&frame);
            ns.process(&mut frame);
        }

        // Regenerate input for final pass
        for i in 0..FRAME_SIZE {
            let t = i as f32 / SAMPLE_RATE_HZ;
            let speech = 0.3 * (2.0 * PI * 200.0 * t).sin()
                + 0.15 * (2.0 * PI * 400.0 * t).sin()
                + 0.08 * (2.0 * PI * 800.0 * t).sin();
            let noise = 0.05 * ((i % 7) as f32 - 3.0) / 3.0;
            frame[i] = speech + noise;
        }

        ns.analyze(&frame);
        ns.process(&mut frame);

        print_vector_f32("NS_SPEECHNOISE_OUTPUT", &frame);
        print_vector_f32("NS_SPEECHNOISE_NOISE", &ns.noise_estimate);
    }
}
