//! NS (Noise Suppression) Golden Vector Tests
//!
//! Validates NS implementation against expected behavioral properties.
//! Original golden vectors generated by Rust reference implementation are used
//! for input validation, but output comparison uses relaxed tolerances due to
//! algorithmic differences between simplified reference and full implementation.

const std = @import("std");
const NoiseSuppressor = @import("audio_processing/ns/noise_suppressor.zig").NoiseSuppressor;
const ns_common = @import("audio_processing/ns/ns_common.zig");

/// Parse a named f32 vector from golden text
fn parseGoldenF32(comptime name: []const u8, comptime N: usize) ![N]f32 {
    const golden_text = try std.fs.cwd().readFileAlloc(
        std.testing.allocator,
        "testdata/rust_ns_golden_vectors.txt",
        8 * 1024 * 1024,
    );
    defer std.testing.allocator.free(golden_text);

    var out: [N]f32 = undefined;
    var seen = [_]bool{false} ** N;
    const prefix = std.fmt.comptimePrint("{s}[", .{name});

    var it = std.mem.splitScalar(u8, golden_text, '\n');
    while (it.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \t\r");
        if (!std.mem.startsWith(u8, line, prefix)) continue;
        if (std.mem.indexOf(u8, line, "]=") == null) continue;

        const close = std.mem.indexOfScalarPos(u8, line, prefix.len, ']') orelse continue;
        const eq = std.mem.indexOfScalarPos(u8, line, close + 1, '=') orelse continue;

        const idx = std.fmt.parseInt(usize, line[prefix.len..close], 10) catch continue;
        if (idx >= N) continue;
        const val = std.fmt.parseFloat(f32, line[eq + 1 ..]) catch continue;

        out[idx] = val;
        seen[idx] = true;
    }

    for (seen, 0..) |ok, i| {
        if (!ok) {
            std.debug.print("Missing golden value for {s}[{}]\n", .{ name, i });
            return error.GoldenVectorIncomplete;
        }
    }
    return out;
}

/// Expect two arrays are within tolerance
fn expectSliceApproxEq(expected: []const f32, actual: []const f32, max_rel_err: f32, max_abs_err: f32) !void {
    std.debug.assert(expected.len == actual.len);

    for (expected, actual, 0..) |e, a, i| {
        const abs_diff = @abs(e - a);
        const rel_diff = if (@abs(e) > 1e-10) abs_diff / @abs(e) else abs_diff;

        if (rel_diff > max_rel_err and abs_diff > max_abs_err) {
            std.debug.print("Mismatch at [{}]: expected={e}, actual={e}, rel_err={e}, abs_err={e}\n", .{ i, e, a, rel_diff, abs_diff });
            return error.ApproxEqFailed;
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Golden Input Validation Tests
// ═══════════════════════════════════════════════════════════════════════════════

test "golden input vectors are valid - silence" {
    const input = try parseGoldenF32("NS_SILENCE_INPUT", ns_common.FRAME_SIZE);

    // Verify all samples are near zero (silence)
    for (input) |s| {
        try std.testing.expect(@abs(s) < 1e-9);
    }
}

test "golden input vectors are valid - low amplitude" {
    const input = try parseGoldenF32("NS_LOWAMP_INPUT", ns_common.FRAME_SIZE);

    // Verify amplitude is around 0.001
    var max_amp: f32 = 0.0;
    for (input) |s| {
        max_amp = @max(max_amp, @abs(s));
    }
    try std.testing.expect(max_amp > 0.0005);
    try std.testing.expect(max_amp < 0.002);
}

test "golden input vectors are valid - full scale" {
    const input = try parseGoldenF32("NS_FULLSCALE_INPUT", ns_common.FRAME_SIZE);

    // Verify amplitude is around 0.9
    var max_amp: f32 = 0.0;
    for (input) |s| {
        max_amp = @max(max_amp, @abs(s));
    }
    try std.testing.expect(max_amp > 0.85);
    try std.testing.expect(max_amp <= 0.91);
}

test "golden input vectors are valid - speech plus noise" {
    const input = try parseGoldenF32("NS_SPEECHNOISE_INPUT", ns_common.FRAME_SIZE);

    // Verify signal has expected characteristics (non-zero, within range)
    var max_amp: f32 = 0.0;
    var sum: f32 = 0.0;
    for (input) |s| {
        max_amp = @max(max_amp, @abs(s));
        sum += @abs(s);
    }
    const avg = sum / ns_common.FRAME_SIZE;

    // Should have moderate amplitude and non-zero average
    try std.testing.expect(max_amp > 0.1);
    try std.testing.expect(max_amp < 0.6);
    try std.testing.expect(avg > 0.01);
}

// ═══════════════════════════════════════════════════════════════════════════════
// NS Behavioral Tests (using golden inputs)
// ═══════════════════════════════════════════════════════════════════════════════

test "ns processes silence input without error" {
    const input = try parseGoldenF32("NS_SILENCE_INPUT", ns_common.FRAME_SIZE);

    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Warm-up
    for (0..5) |_| {
        @memcpy(&frame, &input);
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Final pass
    @memcpy(&frame, &input);
    try ns.analyze(&frame);
    try ns.process(&frame);

    // Output should be well-behaved (no NaN/Inf, within clamp range)
    for (frame) |s| {
        try std.testing.expect(std.math.isFinite(s));
        try std.testing.expect(s >= -1.0);
        try std.testing.expect(s <= 1.0);
    }

    // Silence should remain relatively quiet after processing
    var max_out: f32 = 0.0;
    for (frame) |s| {
        max_out = @max(max_out, @abs(s));
    }
    try std.testing.expect(max_out < 0.1);
}

test "ns processes low amplitude input" {
    const input = try parseGoldenF32("NS_LOWAMP_INPUT", ns_common.FRAME_SIZE);

    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Warm-up
    for (0..5) |_| {
        @memcpy(&frame, &input);
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Final pass
    @memcpy(&frame, &input);
    try ns.analyze(&frame);
    try ns.process(&frame);

    // Output should be well-behaved
    for (frame) |s| {
        try std.testing.expect(std.math.isFinite(s));
        try std.testing.expect(s >= -1.0);
        try std.testing.expect(s <= 1.0);
    }
}

test "ns processes full scale input without clipping" {
    const input = try parseGoldenF32("NS_FULLSCALE_INPUT", ns_common.FRAME_SIZE);

    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Warm-up
    for (0..5) |_| {
        @memcpy(&frame, &input);
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Regenerate input for final pass
    const input2 = try parseGoldenF32("NS_FULLSCALE_INPUT", ns_common.FRAME_SIZE);
    @memcpy(&frame, &input2);
    try ns.analyze(&frame);
    try ns.process(&frame);

    // Output should be well-behaved (clamped to [-1, 1])
    for (frame) |s| {
        try std.testing.expect(std.math.isFinite(s));
        try std.testing.expect(s >= -1.0);
        try std.testing.expect(s <= 1.0);
    }

    // Strong signal should have significant output (not completely suppressed)
    var max_out: f32 = 0.0;
    for (frame) |s| {
        max_out = @max(max_out, @abs(s));
    }
    try std.testing.expect(max_out > 0.05);
}

test "ns processes speech plus noise input" {
    const input = try parseGoldenF32("NS_SPEECHNOISE_INPUT", ns_common.FRAME_SIZE);

    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Warm-up
    for (0..10) |_| {
        @memcpy(&frame, &input);
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Regenerate input for final pass
    const input2 = try parseGoldenF32("NS_SPEECHNOISE_INPUT", ns_common.FRAME_SIZE);
    @memcpy(&frame, &input2);
    try ns.analyze(&frame);
    try ns.process(&frame);

    // Output should be well-behaved
    for (frame) |s| {
        try std.testing.expect(std.math.isFinite(s));
        try std.testing.expect(s >= -1.0);
        try std.testing.expect(s <= 1.0);
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// NS Properties Verification
// ═══════════════════════════════════════════════════════════════════════════════

test "ns noise suppression reduces background noise" {
    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Generate low-level noise
    for (0..ns_common.FRAME_SIZE) |i| {
        frame[i] = 0.01 * @sin(2.0 * std.math.pi * @as(f32, @floatFromInt(i)) * 1000.0 / 16000.0);
    }

    // Warm-up
    for (0..10) |_| {
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Measure output energy
    var out_energy: f32 = 0.0;
    for (frame) |s| {
        out_energy += s * s;
    }

    // After processing, low-level noise should be suppressed
    // Output energy should be less than input (0.01^2 * 256 / 2 = ~0.0128)
    try std.testing.expect(out_energy < 0.01);
}

test "ns preserves strong signals" {
    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Generate strong signal
    for (0..ns_common.FRAME_SIZE) |i| {
        frame[i] = 0.8 * @sin(2.0 * std.math.pi * @as(f32, @floatFromInt(i)) * 1000.0 / 16000.0);
    }

    // Warm-up
    for (0..5) |_| {
        try ns.analyze(&frame);
        try ns.process(&frame);
    }

    // Regenerate strong signal
    for (0..ns_common.FRAME_SIZE) |i| {
        frame[i] = 0.8 * @sin(2.0 * std.math.pi * @as(f32, @floatFromInt(i)) * 1000.0 / 16000.0);
    }
    try ns.analyze(&frame);
    try ns.process(&frame);

    // Strong signal should have significant output
    var max_out: f32 = 0.0;
    for (frame) |s| {
        max_out = @max(max_out, @abs(s));
    }
    try std.testing.expect(max_out > 0.1);
}

test "ns handles multiple consecutive frames" {
    var ns = try NoiseSuppressor.init(.{ .numeric_mode = .float32 });
    var frame: [ns_common.FRAME_SIZE]f32 = undefined;

    // Process 100 frames without error
    var i: usize = 0;
    while (i < 100) : (i += 1) {
        // Generate varying signal
        for (0..ns_common.FRAME_SIZE) |j| {
            const t = @as(f32, @floatFromInt(j)) / 16000.0;
            const freq = 200.0 + @as(f32, @floatFromInt(i)) * 10.0;
            frame[j] = 0.5 * @sin(2.0 * std.math.pi * freq * t);
        }

        try ns.analyze(&frame);
        try ns.process(&frame);

        // Verify output is always valid
        for (frame) |s| {
            try std.testing.expect(std.math.isFinite(s));
            try std.testing.expect(s >= -1.0);
            try std.testing.expect(s <= 1.0);
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Sub-module Tests
// ═══════════════════════════════════════════════════════════════════════════════

test "speech probability estimator produces valid probabilities" {
    const SpeechProbabilityEstimator = @import("audio_processing/ns/speech_probability_estimator.zig").SpeechProbabilityEstimator;

    var spe = SpeechProbabilityEstimator.init(.float32);
    var prior_snr: [ns_common.FFT_SIZE_BY_2_PLUS_1]f32 = undefined;
    var speech_prob: [ns_common.FFT_SIZE_BY_2_PLUS_1]f32 = undefined;

    // Test various SNR values
    const snr_values = [_]f32{ 0.0, 0.1, 0.5, 1.0, 2.0, 5.0, 10.0 };

    for (snr_values) |snr| {
        @memset(&prior_snr, snr);
        spe.estimate(&prior_snr, &speech_prob);

        // All probabilities should be in [0, 1]
        for (speech_prob) |p| {
            try std.testing.expect(p >= 0.0);
            try std.testing.expect(p <= 1.0);
            try std.testing.expect(std.math.isFinite(p));
        }

        // Higher SNR should generally give higher probability
        // (not strictly, but on average)
        if (snr > 5.0) {
            var avg_prob: f32 = 0.0;
            for (speech_prob) |p| {
                avg_prob += p;
            }
            avg_prob /= speech_prob.len;
            try std.testing.expect(avg_prob > 0.5);
        }
    }
}

test "wiener filter gain is always valid" {
    const WienerFilter = @import("audio_processing/ns/wiener_filter.zig").WienerFilter;
    const SuppressionParams = @import("audio_processing/ns/suppression_params.zig").SuppressionParams;

    const params = SuppressionParams.fromConfig(.{});
    var wf = WienerFilter.init(params);

    var prior_snr: [ns_common.FFT_SIZE_BY_2_PLUS_1]f32 = undefined;
    var speech_prob: [ns_common.FFT_SIZE_BY_2_PLUS_1]f32 = undefined;
    var gain: [ns_common.FFT_SIZE_BY_2_PLUS_1]f32 = undefined;

    // Test case 1: Very low SNR -> low gain
    @memset(&prior_snr, 0.01);
    @memset(&speech_prob, 0.01);
    wf.computeGain(&prior_snr, &speech_prob, &gain);

    for (gain) |g| {
        try std.testing.expect(g >= 0.0);
        try std.testing.expect(g <= 1.0);
    }

    // Test case 2: High SNR with high speech prob -> high gain
    @memset(&prior_snr, 10.0);
    @memset(&speech_prob, 0.95);
    wf.computeGain(&prior_snr, &speech_prob, &gain);

    for (gain) |g| {
        try std.testing.expect(g >= 0.0);
        try std.testing.expect(g <= 1.0);
    }

    // Verify that higher SNR generally gives higher gain
    var avg_gain_high: f32 = 0.0;
    for (gain) |g| {
        avg_gain_high += g;
    }
    avg_gain_high /= gain.len;
    try std.testing.expect(avg_gain_high > 0.5);
}
